import { Product, MangoVariety } from '@/types';

export const mangoVarieties: MangoVariety[] = [
  { id: 'himsagar', name: 'Himsagar', nameBn: 'হিমসাগর', origin: 'Rajshahi', originBn: 'রাজশাহী' },
  { id: 'langra', name: 'Langra', nameBn: 'ল্যাংড়া', origin: 'Chapai Nawabganj', originBn: 'চাঁপাইনবাবগঞ্জ' },
  { id: 'fazli', name: 'Fazli', nameBn: 'ফজলি', origin: 'Rajshahi', originBn: 'রাজশাহী' },
  { id: 'amrapali', name: 'Amrapali', nameBn: 'আম্রপালি', origin: 'Rajshahi', originBn: 'রাজশাহী' },
  { id: 'gopalbhog', name: 'Gopalbhog', nameBn: 'গোপালভোগ', origin: 'Chapai Nawabganj', originBn: 'চাঁপাইনবাবগঞ্জ' },
  { id: 'khirsapat', name: 'Khirsapat', nameBn: 'খিরসাপাত', origin: 'Rajshahi', originBn: 'রাজশাহী' },
  { id: 'ashwina', name: 'Ashwina', nameBn: 'আশ্বিনা', origin: 'Satkhira', originBn: 'সাতক্ষীরা' },
];

export const products: Product[] = [
  // RIPE MANGOS
  {
    id: 'p001',
    name: 'Himsagar Mango (Premium)',
    nameBn: 'হিমসাগর আম (প্রিমিয়াম)',
    slug: 'himsagar-mango-premium',
    description: 'The king of mangoes from Rajshahi. Known for its exceptional sweetness, fiber-less pulp, and intoxicating aroma. Hand-picked at perfect ripeness.',
    descriptionBn: 'রাজশাহীর সেরা আমের রাজা হিমসাগর। অসাধারণ মিষ্টতা, আঁশহীন শাঁস এবং মনোমুগ্ধকর সুগন্ধের জন্য বিখ্যাত।',
    price: 580,
    originalPrice: 720,
    discount: 19,
    category: 'ripe',
    variety: mangoVarieties[0],
    images: [
      'https://images.unsplash.com/photo-1601493700631-2b16ec4b4716?w=600',
      'https://images.unsplash.com/photo-1553279768-865429fa0078?w=600',
    ],
    weight: '1 kg',
    weightBn: '১ কেজি',
    stock: 45,
    rating: 4.9,
    reviewCount: 234,
    isOrganic: true,
    isFeatured: true,
    isNew: false,
    isBestseller: true,
    harvestSeason: 'May - June',
    harvestSeasonBn: 'মে - জুন',
    tags: ['premium', 'sweet', 'rajshahi', 'bestseller'],
    nutritionFacts: { calories: 60, carbohydrates: 15, fiber: 1.6, sugar: 14, vitaminC: 36, vitaminA: 10 }
  },
  {
    id: 'p002',
    name: 'Langra Mango',
    nameBn: 'ল্যাংড়া আম',
    slug: 'langra-mango',
    description: 'Famous for its unique sour-sweet flavor and juicy texture. A classic variety from Chapai Nawabganj with unmistakable taste.',
    descriptionBn: 'অনন্য টক-মিষ্টি স্বাদ এবং রসালো টেক্সচারের জন্য বিখ্যাত ল্যাংড়া আম।',
    price: 460,
    originalPrice: 520,
    discount: 12,
    category: 'ripe',
    variety: mangoVarieties[1],
    images: [
      'https://images.unsplash.com/photo-1618160702438-9b02ab6515c9?w=600',
      'https://images.unsplash.com/photo-1605027990121-cbae9e0642df?w=600',
    ],
    weight: '1 kg',
    weightBn: '১ কেজি',
    stock: 30,
    rating: 4.7,
    reviewCount: 189,
    isOrganic: false,
    isFeatured: true,
    isNew: false,
    isBestseller: true,
    harvestSeason: 'June - July',
    harvestSeasonBn: 'জুন - জুলাই',
    tags: ['sweet', 'juicy', 'chapai'],
  },
  {
    id: 'p003',
    name: 'Fazli Mango (Giant)',
    nameBn: 'ফজলি আম (বড়)',
    slug: 'fazli-mango-giant',
    description: 'The giant of mangoes, Fazli is known for its huge size and mild sweet flavor. Perfect for sharing.',
    descriptionBn: 'বিশাল আকারের ফজলি আম তার অনন্য মিষ্টি স্বাদের জন্য বিখ্যাত।',
    price: 380,
    category: 'ripe',
    variety: mangoVarieties[2],
    images: [
      'https://images.unsplash.com/photo-1548013146-72479768bada?w=600',
    ],
    weight: '2 kg',
    weightBn: '২ কেজি',
    stock: 60,
    rating: 4.5,
    reviewCount: 142,
    isOrganic: false,
    isFeatured: false,
    isNew: true,
    isBestseller: false,
    harvestSeason: 'July - August',
    harvestSeasonBn: 'জুলাই - আগস্ট',
    tags: ['giant', 'mild', 'sharing'],
  },
  {
    id: 'p004',
    name: 'Amrapali Mango',
    nameBn: 'আম্রপালি আম',
    slug: 'amrapali-mango',
    description: 'A hybrid variety combining the best of Dasheri and Neelum. Rich in color with balanced sweetness.',
    descriptionBn: 'দশেরি ও নীলামের সেরা গুণাগুণ মিলিয়ে তৈরি হাইব্রিড জাত আম্রপালি।',
    price: 420,
    originalPrice: 500,
    discount: 16,
    category: 'ripe',
    variety: mangoVarieties[3],
    images: [
      'https://images.unsplash.com/photo-1601493700631-2b16ec4b4716?w=600',
    ],
    weight: '1 kg',
    weightBn: '১ কেজি',
    stock: 40,
    rating: 4.6,
    reviewCount: 98,
    isOrganic: true,
    isFeatured: true,
    isNew: false,
    isBestseller: false,
    harvestSeason: 'June - August',
    harvestSeasonBn: 'জুন - আগস্ট',
    tags: ['hybrid', 'sweet', 'organic'],
  },
  {
    id: 'p005',
    name: 'Gopalbhog Mango',
    nameBn: 'গোপালভোগ আম',
    slug: 'gopalbhog-mango',
    description: 'Early season mango with exceptional sweetness. Small to medium sized but packed with intense flavor.',
    descriptionBn: 'মৌসুমের শুরুতেই পাওয়া যায় গোপালভোগ আম। ছোট কিন্তু অসাধারণ মিষ্টি।',
    price: 520,
    category: 'ripe',
    variety: mangoVarieties[4],
    images: [
      'https://images.unsplash.com/photo-1553279768-865429fa0078?w=600',
    ],
    weight: '1 kg',
    weightBn: '১ কেজি',
    stock: 25,
    rating: 4.8,
    reviewCount: 76,
    isOrganic: true,
    isFeatured: false,
    isNew: true,
    isBestseller: false,
    harvestSeason: 'May',
    harvestSeasonBn: 'মে',
    tags: ['early', 'sweet', 'small', 'organic'],
  },

  // RAW MANGOS
  {
    id: 'p006',
    name: 'Raw Green Mango (Cooking)',
    nameBn: 'কাঁচা আম (রান্নার জন্য)',
    slug: 'raw-green-mango-cooking',
    description: 'Perfect for making pickles, chutneys, and traditional Bengali dishes. Firm, sour, and fresh from the orchard.',
    descriptionBn: 'আচার, চাটনি এবং ঐতিহ্যবাহী রান্নার জন্য আদর্শ কাঁচা আম।',
    price: 180,
    category: 'raw',
    variety: mangoVarieties[0],
    images: [
      'https://images.unsplash.com/photo-1605027990121-cbae9e0642df?w=600',
    ],
    weight: '1 kg',
    weightBn: '১ কেজি',
    stock: 80,
    rating: 4.4,
    reviewCount: 112,
    isOrganic: false,
    isFeatured: false,
    isNew: false,
    isBestseller: true,
    harvestSeason: 'April - May',
    harvestSeasonBn: 'এপ্রিল - মে',
    tags: ['raw', 'cooking', 'sour', 'pickle'],
  },
  {
    id: 'p007',
    name: 'Organic Raw Mango Pack',
    nameBn: 'অর্গানিক কাঁচা আম প্যাক',
    slug: 'organic-raw-mango-pack',
    description: 'Certified organic raw mangoes, perfect for health drinks, salads, and traditional recipes.',
    descriptionBn: 'সার্টিফাইড অর্গানিক কাঁচা আম, স্বাস্থ্যকর পানীয় ও রান্নার জন্য উপযুক্ত।',
    price: 280,
    originalPrice: 320,
    discount: 12,
    category: 'raw',
    variety: mangoVarieties[1],
    images: [
      'https://images.unsplash.com/photo-1618160702438-9b02ab6515c9?w=600',
    ],
    weight: '2 kg',
    weightBn: '২ কেজি',
    stock: 55,
    rating: 4.6,
    reviewCount: 87,
    isOrganic: true,
    isFeatured: true,
    isNew: false,
    isBestseller: false,
    harvestSeason: 'March - May',
    harvestSeasonBn: 'মার্চ - মে',
    tags: ['organic', 'raw', 'healthy'],
  },

  // DRIED MANGO
  {
    id: 'p008',
    name: 'Sun-Dried Mango Slices',
    nameBn: 'রোদে শুকানো আমের স্লাইস',
    slug: 'sun-dried-mango-slices',
    description: 'Naturally sun-dried mango slices with no added sugar or preservatives. Rich in fiber and nutrients.',
    descriptionBn: 'কোনো চিনি বা প্রিজার্ভেটিভ ছাড়া প্রাকৃতিকভাবে রোদে শুকানো আমের স্লাইস।',
    price: 320,
    originalPrice: 380,
    discount: 16,
    category: 'dried',
    variety: mangoVarieties[2],
    images: [
      'https://images.unsplash.com/photo-1548013146-72479768bada?w=600',
    ],
    weight: '250g',
    weightBn: '২৫০ গ্রাম',
    stock: 70,
    rating: 4.7,
    reviewCount: 156,
    isOrganic: true,
    isFeatured: true,
    isNew: false,
    isBestseller: true,
    harvestSeason: 'Year Round',
    harvestSeasonBn: 'সারা বছর',
    tags: ['dried', 'healthy', 'snack', 'no-sugar'],
  },

  // MANGO JUICE
  {
    id: 'p009',
    name: 'Pure Himsagar Mango Juice',
    nameBn: 'খাঁটি হিমসাগর আমের জুস',
    slug: 'pure-himsagar-mango-juice',
    description: '100% pure mango juice extracted from fresh Himsagar mangoes. No added sugar, no preservatives.',
    descriptionBn: '১০০% খাঁটি হিমসাগর আম থেকে তৈরি জুস। কোনো চিনি বা প্রিজার্ভেটিভ নেই।',
    price: 250,
    category: 'juice',
    variety: mangoVarieties[0],
    images: [
      'https://images.unsplash.com/photo-1601493700631-2b16ec4b4716?w=600',
    ],
    weight: '500ml',
    weightBn: '৫০০ মিলি',
    stock: 100,
    rating: 4.8,
    reviewCount: 203,
    isOrganic: true,
    isFeatured: true,
    isNew: true,
    isBestseller: false,
    harvestSeason: 'Year Round',
    harvestSeasonBn: 'সারা বছর',
    tags: ['juice', 'pure', 'no-sugar', 'fresh'],
  },

  // MANGO PICKLE
  {
    id: 'p010',
    name: 'Traditional Mango Pickle (Achar)',
    nameBn: 'ঐতিহ্যবাহী আমের আচার',
    slug: 'traditional-mango-pickle',
    description: 'Traditional Bengali mango pickle made with authentic spices and mustard oil. A family recipe passed down for generations.',
    descriptionBn: 'খাঁটি মশলা ও সরিষার তেল দিয়ে তৈরি ঐতিহ্যবাহী বাংলা আমের আচার।',
    price: 180,
    category: 'pickle',
    variety: mangoVarieties[1],
    images: [
      'https://images.unsplash.com/photo-1605027990121-cbae9e0642df?w=600',
    ],
    weight: '400g',
    weightBn: '৪০০ গ্রাম',
    stock: 90,
    rating: 4.9,
    reviewCount: 321,
    isOrganic: false,
    isFeatured: false,
    isNew: false,
    isBestseller: true,
    harvestSeason: 'Year Round',
    harvestSeasonBn: 'সারা বছর',
    tags: ['pickle', 'traditional', 'achar', 'spicy'],
  },
  {
    id: 'p011',
    name: 'Khirsapat Mango',
    nameBn: 'খিরসাপাত আম',
    slug: 'khirsapat-mango',
    description: 'Also known as Kheer Shapath, this variety is famous for its creamy texture and unparalleled sweetness.',
    descriptionBn: 'খিরসাপাত আম তার ক্রিমি টেক্সচার এবং অতুলনীয় মিষ্টতার জন্য বিখ্যাত।',
    price: 650,
    originalPrice: 780,
    discount: 17,
    category: 'ripe',
    variety: mangoVarieties[5],
    images: [
      'https://images.unsplash.com/photo-1553279768-865429fa0078?w=600',
    ],
    weight: '1 kg',
    weightBn: '১ কেজি',
    stock: 20,
    rating: 5.0,
    reviewCount: 89,
    isOrganic: true,
    isFeatured: true,
    isNew: false,
    isBestseller: true,
    harvestSeason: 'May - June',
    harvestSeasonBn: 'মে - জুন',
    tags: ['premium', 'creamy', 'sweet', 'rare'],
  },
  {
    id: 'p012',
    name: 'Ashwina Late Season Mango',
    nameBn: 'আশ্বিনা আম',
    slug: 'ashwina-mango',
    description: 'The late season mango that extends the mango season into October. From the coastal region of Satkhira.',
    descriptionBn: 'মৌসুমের শেষে অক্টোবর পর্যন্ত পাওয়া যায় সাতক্ষীরার আশ্বিনা আম।',
    price: 350,
    category: 'ripe',
    variety: mangoVarieties[6],
    images: [
      'https://images.unsplash.com/photo-1618160702438-9b02ab6515c9?w=600',
    ],
    weight: '1 kg',
    weightBn: '১ কেজি',
    stock: 35,
    rating: 4.4,
    reviewCount: 67,
    isOrganic: false,
    isFeatured: false,
    isNew: true,
    isBestseller: false,
    harvestSeason: 'September - October',
    harvestSeasonBn: 'সেপ্টেম্বর - অক্টোবর',
    tags: ['late-season', 'satkhira'],
  },
];

export const getFeaturedProducts = () => products.filter(p => p.isFeatured);
export const getBestsellerProducts = () => products.filter(p => p.isBestseller);
export const getNewProducts = () => products.filter(p => p.isNew);
export const getProductsByCategory = (category: string) =>
  category === 'all' ? products : products.filter(p => p.category === category);
export const getProductBySlug = (slug: string) => products.find(p => p.slug === slug);
